---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://s3.amazonaws.com/gsc-vagrant-boxes/ubuntu-12.04.2-server-amd64.box
    require_chef_omnibus: '10.26.0'
    provider: vmware_fusion
    customize:
      memsize: 1024

suites:
- name: default
  run_list: ["recipe[avahi_test]"]
  attributes: {}
